version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  labels:
  - dependencies
  ignore:
  - dependency-name: "@babel/*"
    versions:
    - ">= 0"
  - dependency-name: babel-plugin-preval
    versions:
    - ">= 3.0"
  - dependency-name: core-js
    versions:
    - ">= 0"
  - dependency-name: "@date-io/*"
    versions:
    - ">= 0"
  - dependency-name: jss-*
    versions:
    - ">= 0"
  - dependency-name: raw-loader
    versions:
    - ">= 0"
  - dependency-name: react-dom
    versions:
    - ">= 0"
  - dependency-name: react-is
    versions:
    - ">= 0"
  - dependency-name: react-test-renderer
    versions:
    - ">= 0"
  - dependency-name: tslint
    versions:
    - 5.x
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - ">= 0"
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@chakra-ui/system"
    versions:
    - 1.1.7
    - 1.3.1
    - 1.5.1
  - dependency-name: clean-css
    versions:
    - 5.0.1
    - 5.1.0
  - dependency-name: sinon
    versions:
    - 9.2.4
  - dependency-name: webpack
    versions:
    - 5.17.0
